
package UNO;

import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Akshat Gupta 
 * @author Varun Sahni
 */
public class CardConfirmation extends javax.swing.JFrame {

   String cardImage = "";
   Game game;
   ArrayList<CardInfo> playerHand;
   int choice;
   ArrayList<JButton> cardButtons;
   
   PlayArea  gameStage;
   JButton discardPile;
   CardInfo.Color declaredColor;
   
   public CardConfirmation(){}
   
    public CardConfirmation(String cardName, Game game,int index, ArrayList<JButton> cardButtons , PlayArea gameStage , JButton discardPile) {
        initComponents();
        cardImage = cardName;
        this.game = game;
        playerHand = game.getPlayerHand(game.getCurrentPlayer());
        choice = index;
        this.cardButtons = cardButtons;
        card.setIcon(new javax.swing.ImageIcon("C:\\Users\\91870\\OneDrive\\Documents\\NetBeansProjects\\UNO\\src\\main\\java\\UNO\\cardsImage\\" + cardImage + ".png"));
        this.gameStage = gameStage;
        this.discardPile = discardPile;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        useCard = new javax.swing.JButton();
        card = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Message");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        cancel.setBackground(new java.awt.Color(51, 243, 33));
        cancel.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        useCard.setBackground(new java.awt.Color(51, 243, 33));
        useCard.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        useCard.setForeground(new java.awt.Color(255, 255, 255));
        useCard.setText("Use Card");
        useCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useCardActionPerformed(evt);
            }
        });

        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setFont(new java.awt.Font("Century", 0, 48)); // NOI18N
        card.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(useCard, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useCard, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void useCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useCardActionPerformed
      ChooseWildColor pickColor = new ChooseWildColor(this);
      declaredColor = pickColor.choseColor(playerHand.get(choice));
      if( declaredColor != null){
          try{
              game.submitPlayerCard(game.getCurrentPlayer(), playerHand.get(choice), declaredColor);
          }catch(InvalidColorSubmissionException e){
          Logger.getLogger(CardConfirmation.class.getName()).log(Level.SEVERE,null,e);}
          catch (InvalidValueSubmissionException e){
          Logger.getLogger(CardConfirmation.class.getName()).log(Level.SEVERE,null,e);}
          catch ( InvalidPlayerTurnException e){
          Logger.getLogger(CardConfirmation.class.getName()).log(Level.SEVERE,null,e);}
          this.revalidate();
          if(declaredColor != CardInfo.Color.Wild){
              gameStage.setPlayerIdName(game.getCurrentPlayer());
              gameStage.setButtonIcons();
              discardPile.setIcon(new javax.swing.ImageIcon("C:\\Users\\91870\\OneDrive\\Documents\\NetBeansProjects\\UNO\\src\\main\\java\\UNO\\cardsImage\\" + game.getTopCardImage()));
              this.dispose();
          }
      }
    }//GEN-LAST:event_useCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardConfirmation().setVisible(true);
            }
        });
    }

    // VCalibribles declaration - do not modify//GEN-BEGIN:vCalibribles
    private javax.swing.JButton cancel;
    private javax.swing.JLabel card;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton useCard;
    // End of vCalibribles declaration//GEN-END:vCalibribles
}
