
package UNO;

import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Akshat Gupta
 * @author Varun Sahni
 */
public class ChooseWildColor extends javax.swing.JFrame {

    private CardInfo.Color wildColor = null;
    Boolean allow = false;
    CardConfirmation popUp;
    
    public ChooseWildColor() {
        initComponents();
    }
    
    public ChooseWildColor(CardConfirmation popUp) {
        initComponents();
        this.popUp=popUp;
    }
    
    public CardInfo.Color choseColor(CardInfo card){
        if(card.getColor() == CardInfo.Color.Wild){
            this.setBounds(100,150,450,400);
            this.setVisible(true);
            this.setResizable(false);
        }
        
        return card.getColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        red = new javax.swing.JButton();
        blue = new javax.swing.JButton();
        green = new javax.swing.JButton();
        yellow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE THE COLOR");

        red.setBackground(new java.awt.Color(252, 0, 0));
        red.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        red.setText("RED");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });

        blue.setBackground(new java.awt.Color(255, 255, 0));
        blue.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        blue.setText("YELLOW");
        blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueActionPerformed(evt);
            }
        });

        green.setBackground(new java.awt.Color(0, 238, 0));
        green.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        green.setText("GREEN");
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });

        yellow.setBackground(new java.awt.Color(0, 0, 236));
        yellow.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        yellow.setText("BLUE");
        yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(green, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(yellow, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(red, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(red, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellow, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(green, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueActionPerformed
          wildColor = CardInfo.Color.Blue;
        JLabel message = new JLabel("COLOR TO BE PLAYED IS BLUE NOW!!");
        message.setFont(new Font("Calibri",Font.BOLD,24));
        JOptionPane.showMessageDialog(null,message);
        allow = true;
        this.dispose(); 
        popUp.declaredColor = CardInfo.Color.Blue;
        popUp.gameStage.setPlayerIdName(popUp.game.getCurrentPlayer()); 
        popUp.gameStage.setButtonIcons();
        popUp.discardPile.setIcon(new javax.swing.ImageIcon("C:\\Users\\91870\\OneDrive\\Documents\\NetBeansProjects\\UNO\\src\\main\\java\\UNO\\cardsImage\\" + popUp.game.getTopCardImage()));
        popUp.game.setCardColor(CardInfo.Color.Blue);
        popUp.dispose();
    }//GEN-LAST:event_blueActionPerformed

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        wildColor = CardInfo.Color.Green;
        JLabel message = new JLabel("COLOR TO BE PLAYED IS GREEN NOW!!");
        message.setFont(new Font("Calibri",Font.BOLD,24));
        JOptionPane.showMessageDialog(null,message);
        allow = true;
        this.dispose(); 
        popUp.declaredColor = CardInfo.Color.Green;
        popUp.gameStage.setPlayerIdName(popUp.game.getCurrentPlayer()); 
        popUp.gameStage.setButtonIcons();
        popUp.discardPile.setIcon(new javax.swing.ImageIcon("C:\\Users\\91870\\OneDrive\\Documents\\NetBeansProjects\\UNO\\src\\main\\java\\UNO\\cardsImage\\" + popUp.game.getTopCardImage()));
        popUp.game.setCardColor(CardInfo.Color.Green);
        popUp.dispose();
    }//GEN-LAST:event_greenActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        wildColor = CardInfo.Color.Red;
        JLabel message = new JLabel("COLOR TO BE PLAYED IS RED NOW!!");
        message.setFont(new Font("Calibri",Font.BOLD,24));
        JOptionPane.showMessageDialog(null,message);
        allow = true;
        this.dispose(); 
        popUp.declaredColor = CardInfo.Color.Red;
        popUp.gameStage.setPlayerIdName(popUp.game.getCurrentPlayer()); 
        popUp.gameStage.setButtonIcons();
        popUp.discardPile.setIcon(new javax.swing.ImageIcon("C:\\Users\\91870\\OneDrive\\Documents\\NetBeansProjects\\UNO\\src\\main\\java\\UNO\\cardsImage\\" + popUp.game.getTopCardImage()));
        popUp.game.setCardColor(CardInfo.Color.Red);
        popUp.dispose();
    }//GEN-LAST:event_redActionPerformed

    private void yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowActionPerformed
        wildColor = CardInfo.Color.Yellow;
        JLabel message = new JLabel("COLOR TO BE PLAYED IS YELLOW NOW!!");
        message.setFont(new Font("Calibri",Font.BOLD,24));
        JOptionPane.showMessageDialog(null,message);
        allow = true;
        this.dispose(); 
        popUp.declaredColor = CardInfo.Color.Yellow;
        popUp.gameStage.setPlayerIdName(popUp.game.getCurrentPlayer()); 
        popUp.gameStage.setButtonIcons();
        popUp.discardPile.setIcon(new javax.swing.ImageIcon("C:\\Users\\91870\\OneDrive\\Documents\\NetBeansProjects\\UNO\\src\\main\\java\\UNO\\cardsImage\\" + popUp.game.getTopCardImage()));
        popUp.game.setCardColor(CardInfo.Color.Yellow);
        popUp.dispose();
    }//GEN-LAST:event_yellowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseWildColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseWildColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseWildColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseWildColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChooseWildColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blue;
    private javax.swing.JButton green;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton red;
    private javax.swing.JButton yellow;
    // End of variables declaration//GEN-END:variables
}
